version: '3'

services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: buzznbloom
    restart: always

  wordpress:
    platform: linux/arm64
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ''
      WORDPRESS_DB_NAME: buzznbloom
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://buzznbloom.test');
        define('WP_SITEURL','http://buzznbloom.test');
    restart: always

volumes:
  db_data: {} 